#!/usr/bin/env python3
"""
generate_cases.py — synthetic DNS TTL boundary cases
No network, no DNS queries, deterministic seed 42.
"""
import json

cases = [
    # positive inside TTL — fresh serve
    {
        "case_id": "c01_positive_inside_ttl",
        "category": "positive",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 200,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "must_not_serve_stale": False,
            "serve_stale_allowed": False,
            "may_evict_early": True,
            "ttl_upper_bound": True,
        },
        "reason": "inside TTL 100/300 fresh"
    },
    {
        "case_id": "c02_positive_inside_ttl_near_expiry",
        "category": "positive",
        "qname": "example.com.",
        "qtype": "AAAA",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 299,
        "elapsed": 299,
        "expired": False,
        "remaining": 1,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "must_not_serve_stale": False,
            "serve_stale_allowed": False,
            "may_evict_early": True,
            "ttl_upper_bound": True,
        },
        "reason": "1s remaining still fresh"
    },
    # resolver evicts / refetches before TTL expiry — allowed (upper bound)
    {
        "case_id": "c03_early_evict_before_expiry",
        "category": "implementation_freedom",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 3600,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 3500,
        "rrset_ttls": [3600],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 3600,
        "ttl_zero": False,
        "action": "resolver_evicts_at_100_and_refetches",
        "expect": {
            "may_serve_from_cache": True,
            "must_not_serve_stale": False,
            "serve_stale_allowed": False,
            "may_evict_early": True,
            "ttl_upper_bound": True,
            "early_evict_compliant": True,
        },
        "reason": "RFC2181 maximum not mandatory — early evict allowed"
    },
    {
        "case_id": "c04_early_refresh_allowed",
        "category": "implementation_freedom",
        "qname": "refresh.example.com.",
        "qtype": "A",
        "stored_ttl": 86400,
        "stored_at": 0,
        "now": 3600,
        "elapsed": 3600,
        "expired": False,
        "remaining": 82800,
        "rrset_ttls": [86400],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 86400,
        "ttl_zero": False,
        "action": "resolver_refreshes_at_3600_despite_ttl",
        "expect": {
            "may_serve_from_cache": True,
            "must_not_serve_stale": False,
            "serve_stale_allowed": False,
            "may_evict_early": True,
            "ttl_upper_bound": True,
            "early_evict_compliant": True,
        },
        "reason": "no floor on refetching unexpired RRs"
    },
    # expired with authority reachable — must NOT serve stale ordinarily
    {
        "case_id": "c05_expired_authority_reachable",
        "category": "expired_ordinary",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 400,
        "elapsed": 400,
        "expired": True,
        "remaining": -100,
        "stale_age": 100,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": True,
        "max_stale": 86400,
        "failure_recheck_elapsed": 100,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": True,
            "serve_stale_allowed": False,
            "may_evict_early": True,
            "ttl_upper_bound": True,
        },
        "reason": "expired and authority reachable — ordinary stale NOT allowed"
    },
    {
        "case_id": "c06_expired_authority_reachable_nodata",
        "category": "expired_ordinary",
        "qname": "example.com.",
        "qtype": "TXT",
        "stored_ttl": 60,
        "stored_at": 0,
        "now": 120,
        "elapsed": 120,
        "expired": True,
        "remaining": -60,
        "stale_age": 60,
        "rrset_ttls": [60],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": True,
        "max_stale": 86400,
        "failure_recheck_elapsed": 100,
        "implementation_max_ttl": 604800,
        "received_ttl": 60,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": True,
            "serve_stale_allowed": False,
            "may_evict_early": True,
            "ttl_upper_bound": True,
        },
        "reason": "expired TXT but reachable — must refetch not serve stale"
    },
    # expired retained and served under RFC8767 failure conditions
    {
        "case_id": "c07_stale_8767_authority_unreachable",
        "category": "serve_stale",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 400,
        "elapsed": 400,
        "expired": True,
        "remaining": -100,
        "stale_age": 100,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": False,
        "authority_rcode": None,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": True,
        "max_stale": 86400,
        "failure_recheck_elapsed": 40,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "stale_response_ttl": 30,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": False,
            "serve_stale_allowed": True,
            "stale_ttl_must_be_positive": True,
            "stale_ttl_recommended": 30,
            "ttl_upper_bound": True,
        },
        "reason": "RFC8767: expired but authority unreachable + RD + within max-stale"
    },
    {
        "case_id": "c08_stale_8767_servfail_treated_as_failure",
        "category": "serve_stale",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 500,
        "elapsed": 500,
        "expired": True,
        "remaining": -200,
        "stale_age": 200,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 2,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": True,
        "max_stale": 86400,
        "failure_recheck_elapsed": 60,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "stale_response_ttl": 30,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": False,
            "serve_stale_allowed": True,
            "stale_ttl_must_be_positive": True,
            "stale_ttl_recommended": 30,
            "ttl_upper_bound": True,
        },
        "reason": "RCODE SERVFAIL treated as failure to refresh — stale allowed"
    },
    {
        "case_id": "c09_stale_8767_within_max_stale_boundary",
        "category": "serve_stale",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 80000,
        "elapsed": 80000,
        "expired": True,
        "remaining": -79700,
        "stale_age": 79700,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": False,
        "authority_rcode": None,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": True,
        "max_stale": 86400,
        "failure_recheck_elapsed": 40,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "stale_response_ttl": 30,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": False,
            "serve_stale_allowed": True,
            "stale_ttl_must_be_positive": True,
            "ttl_upper_bound": True,
        },
        "reason": "stale age 79700 within max_stale 86400 — still allowed"
    },
    {
        "case_id": "c10_stale_beyond_max_stale",
        "category": "serve_stale",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 90000,
        "elapsed": 90000,
        "expired": True,
        "remaining": -89700,
        "stale_age": 89700,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": False,
        "authority_rcode": None,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": True,
        "max_stale": 86400,
        "failure_recheck_elapsed": 40,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": True,
            "serve_stale_allowed": False,
            "ttl_upper_bound": True,
        },
        "reason": "beyond max-stale — must be purged, not served"
    },
    # expired when recursion not requested — must not serve stale
    {
        "case_id": "c11_expired_no_rd_flag",
        "category": "serve_stale",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 400,
        "elapsed": 400,
        "expired": True,
        "remaining": -100,
        "stale_age": 100,
        "rrset_ttls": [300],
        "rd_flag": False,
        "authority_reachable": False,
        "authority_rcode": None,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": True,
        "max_stale": 86400,
        "failure_recheck_elapsed": 40,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": True,
            "serve_stale_allowed": False,
            "ttl_upper_bound": True,
            "no_rd_means_no_stale": True,
        },
        "reason": "RD=0 — RFC8767 says return referral not stale"
    },
    {
        "case_id": "c12_fresh_no_rd_still_fresh_serve",
        "category": "serve_stale",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 200,
        "rrset_ttls": [300],
        "rd_flag": False,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": True,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "must_not_serve_stale": False,
            "serve_stale_allowed": False,
            "ttl_upper_bound": True,
        },
        "reason": "RD=0 but still inside TTL — fresh cache hit ok (iterative not needed)"
    },
    # TTL 0 — not cached
    {
        "case_id": "c13_ttl_zero_not_cached",
        "category": "ttl_zero",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 0,
        "stored_at": 0,
        "now": 0,
        "elapsed": 0,
        "expired": True,
        "remaining": 0,
        "stale_age": 0,
        "rrset_ttls": [0],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": True,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 0,
        "ttl_zero": True,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": True,
            "serve_stale_allowed": False,
            "ttl_zero_no_cache": True,
            "ttl_upper_bound": True,
        },
        "reason": "TTL 0 — usable only for transaction, not cached"
    },
    {
        "case_id": "c14_ttl_zero_expired_immediate",
        "category": "ttl_zero",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 0,
        "stored_at": 0,
        "now": 1,
        "elapsed": 1,
        "expired": True,
        "remaining": -1,
        "stale_age": 1,
        "rrset_ttls": [0],
        "rd_flag": True,
        "authority_reachable": False,
        "authority_rcode": None,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": True,
        "max_stale": 86400,
        "failure_recheck_elapsed": 40,
        "implementation_max_ttl": 604800,
        "received_ttl": 0,
        "ttl_zero": True,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": True,
            "serve_stale_allowed": False,
            "ttl_zero_no_cache": True,
            "ttl_upper_bound": True,
        },
        "reason": "TTL 0 never enters cache — no stale to serve"
    },
    # authoritative RRset containing differing TTLs
    {
        "case_id": "c15_rrset_differing_ttls",
        "category": "rrset",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 200,
        "elapsed": 200,
        "expired": False,
        "remaining": 100,
        "rrset_ttls": [300, 400, 500],
        "rrset_effective_ttl": 300,
        "rrset_normalized": True,
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 500,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "rrset_ttls_differ": True,
            "rrset_effective_ttl": 300,
            "rrset_must_normalize": True,
            "ttl_upper_bound": True,
        },
        "reason": "RFC2181 §5.2 RRset differing TTLs — effective is min"
    },
    {
        "case_id": "c16_rrset_uniform_ttls",
        "category": "rrset",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 200,
        "rrset_ttls": [300, 300, 300],
        "rrset_effective_ttl": 300,
        "rrset_normalized": False,
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "rrset_ttls_differ": False,
            "rrset_effective_ttl": 300,
            "ttl_upper_bound": True,
        },
        "reason": "uniform RRset TTL — no normalization needed"
    },
    {
        "case_id": "c17_rrset_single_rr",
        "category": "rrset",
        "qname": "single.example.com.",
        "qtype": "A",
        "stored_ttl": 60,
        "stored_at": 0,
        "now": 30,
        "elapsed": 30,
        "expired": False,
        "remaining": 30,
        "rrset_ttls": [60],
        "rrset_effective_ttl": 60,
        "rrset_normalized": False,
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 60,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "rrset_ttls_differ": False,
            "rrset_effective_ttl": 60,
            "ttl_upper_bound": True,
        },
        "reason": "single RR — trivial RRset"
    },
    # negative caching
    {
        "case_id": "c18_negative_nxdomain_soa_minimum_smaller",
        "category": "negative",
        "qname": "nonexistent.example.com.",
        "qtype": "A",
        "stored_ttl": None,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 200,
        "rrset_ttls": [],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 3,
        "soa_ttl": 3600,
        "soa_minimum": 300,
        "negative_type": "NXDOMAIN",
        "negative_ttl": 300,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": None,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "negative_cache_ttl": 300,
            "negative_ttl_is_soa_derived": True,
            "negative_not_positive_ttl": True,
        },
        "reason": "RFC2308: negative TTL = min(SOA TTL, MINIMUM) = min(3600,300)=300"
    },
    {
        "case_id": "c19_negative_nxdomain_soa_ttl_smaller",
        "category": "negative",
        "qname": "nonexistent.example.com.",
        "qtype": "A",
        "stored_ttl": None,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 100,
        "rrset_ttls": [],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 3,
        "soa_ttl": 300,
        "soa_minimum": 3600,
        "negative_type": "NXDOMAIN",
        "negative_ttl": 300,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": None,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "negative_cache_ttl": 300,
            "negative_ttl_is_soa_derived": True,
            "negative_not_positive_ttl": True,
        },
        "reason": "min(300,3600)=300 — SOA TTL smaller case"
    },
    {
        "case_id": "c20_negative_nodata",
        "category": "negative",
        "qname": "example.com.",
        "qtype": "TXT",
        "stored_ttl": None,
        "stored_at": 0,
        "now": 50,
        "elapsed": 50,
        "expired": False,
        "remaining": 250,
        "rrset_ttls": [],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": 900,
        "soa_minimum": 300,
        "negative_type": "NODATA",
        "negative_ttl": 300,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": None,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "negative_cache_ttl": 300,
            "negative_ttl_is_soa_derived": True,
            "negative_not_positive_ttl": True,
        },
        "reason": "NODATA negative — also SOA derived"
    },
    {
        "case_id": "c21_negative_expired_must_refetch",
        "category": "negative",
        "qname": "nonexistent.example.com.",
        "qtype": "A",
        "stored_ttl": None,
        "stored_at": 0,
        "now": 400,
        "elapsed": 400,
        "expired": True,
        "remaining": -100,
        "stale_age": 100,
        "rrset_ttls": [],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 3,
        "soa_ttl": 3600,
        "soa_minimum": 300,
        "negative_type": "NXDOMAIN",
        "negative_ttl": 300,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": None,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": False,
            "negative_cache_ttl": 300,
            "negative_expired": True,
            "must_not_serve_stale": True,
            "negative_ttl_is_soa_derived": True,
        },
        "reason": "negative cache expired — same upper-bound rule"
    },
    {
        "case_id": "c22_negative_soa_equal",
        "category": "negative",
        "qname": "nonexistent2.example.com.",
        "qtype": "A",
        "stored_ttl": None,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 500,
        "rrset_ttls": [],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 3,
        "soa_ttl": 600,
        "soa_minimum": 600,
        "negative_type": "NXDOMAIN",
        "negative_ttl": 600,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": None,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "negative_cache_ttl": 600,
            "negative_ttl_is_soa_derived": True,
        },
        "reason": "SOA TTL == MINIMUM — negative TTL 600"
    },
    # implementation clamps excessively large TTL
    {
        "case_id": "c23_clamp_large_ttl",
        "category": "clamp",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 604800,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 604700,
        "rrset_ttls": [604800],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 2147483647,
        "effective_ttl": 604800,
        "clamped": True,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "clamped": True,
            "effective_ttl": 604800,
            "received_ttl": 2147483647,
            "ttl_upper_bound": True,
        },
        "reason": "received 2^31-1 clamped to 7 days per RFC8767 cap"
    },
    {
        "case_id": "c24_clamp_moderately_large",
        "category": "clamp",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 604800,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 604700,
        "rrset_ttls": [604800],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 1000000,
        "effective_ttl": 604800,
        "clamped": True,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "clamped": True,
            "effective_ttl": 604800,
            "received_ttl": 1000000,
        },
        "reason": "1M > 604800 clamped"
    },
    {
        "case_id": "c25_no_clamp_small_ttl",
        "category": "clamp",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 200,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "effective_ttl": 300,
        "clamped": False,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "clamped": False,
            "effective_ttl": 300,
        },
        "reason": "300 < cap — not clamped"
    },
    # additional boundary cases
    {
        "case_id": "c26_stale_disabled_config",
        "category": "serve_stale",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 400,
        "elapsed": 400,
        "expired": True,
        "remaining": -100,
        "stale_age": 100,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": False,
        "authority_rcode": None,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 40,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": True,
            "serve_stale_allowed": False,
        },
        "reason": "stale disabled — even with failure, no stale"
    },
    {
        "case_id": "c27_stale_wrong_rcode_noerror_refreshes",
        "category": "serve_stale",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 400,
        "elapsed": 400,
        "expired": True,
        "remaining": -100,
        "stale_age": 100,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": True,
        "max_stale": 86400,
        "failure_recheck_elapsed": 40,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": True,
            "serve_stale_allowed": False,
            "rcode_refreshes": True,
        },
        "reason": "NoError AA refreshes — not a failure, stale not allowed"
    },
    {
        "case_id": "c28_negative_not_stale_interchangeable",
        "category": "negative",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 200,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": 900,
        "soa_minimum": 300,
        "negative_type": None,
        "negative_ttl": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": True,
            "negative_ttl_is_soa_derived": False,
            "positive_ttl_is_rr_ttl": True,
        },
        "reason": "positive cache TTL comes from RR TTL, not SOA — boundary marker"
    },
    {
        "case_id": "c29_cloudflare_memory_is_deployment",
        "category": "deployment",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 100,
        "elapsed": 100,
        "expired": False,
        "remaining": 200,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "cloudflare_memory_savings": "100TB fleet measurement",
        "cloudflare_is_semantic_permission": False,
        "expect": {
            "may_serve_from_cache": True,
            "deployment_measurement": True,
            "not_semantic_permission": True,
        },
        "reason": "Cloudflare 100TB is deployment measurement, not TTL semantics permission"
    },
    {
        "case_id": "c30_exact_ttl_boundary",
        "category": "positive",
        "qname": "example.com.",
        "qtype": "A",
        "stored_ttl": 300,
        "stored_at": 0,
        "now": 300,
        "elapsed": 300,
        "expired": True,
        "remaining": 0,
        "stale_age": 0,
        "rrset_ttls": [300],
        "rd_flag": True,
        "authority_reachable": True,
        "authority_rcode": 0,
        "soa_ttl": None,
        "soa_minimum": None,
        "negative_type": None,
        "stale_config_enabled": False,
        "max_stale": 86400,
        "failure_recheck_elapsed": 0,
        "implementation_max_ttl": 604800,
        "received_ttl": 300,
        "ttl_zero": False,
        "expect": {
            "may_serve_from_cache": False,
            "must_not_serve_stale": True,
            "serve_stale_allowed": False,
            "exact_expiry": True,
        },
        "reason": "now == stored_at+TTL — exactly expired, must not serve ordinarily"
    },
]

import pathlib
out = pathlib.Path(__file__).parent / "cases.json"
with open(out, "w") as f:
    json.dump({"seed": 42, "count": len(cases), "cases": cases}, f, indent=2)

print(f"Wrote {len(cases)} cases to {out}")
